language:
    - cpp
sudo: required

matrix:
  include:
    # linux with gcc default (4.8)
    - os: linux
      dist: trusty
      compiler: gcc
    # osx with xcode8.3/clang
    - os: osx
      osx_image: xcode8.3
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"
    # uninstalling oclint, as it's preinstalled and conflicts with all versions of gcc
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew cask uninstall oclint || true
    brew update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

install:
  - ./.ci/install-deps.sh

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig; fi

script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        ./waf configure --prefix=/usr --alsa --classic --dbus;
        ./waf -v build;
      fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        CXXFLAGS="${CXXFLAGS} -flax-vector-conversions" ./waf configure;
        CXXFLAGS="${CXXFLAGS} -flax-vector-conversions" ./waf -v build;
      fi
    - sudo ./waf -v install
# run very basic tests
    - sudo .ci/test_run.sh

branches:
  only:
    - /.*/

notifications:
  email: false
# vim:set ts=2 sw=2 et:
